### ISSUE TITLE
How to compare two images 

### ISSUE THREAD

**Issue by rohitsinha54** [hhatto/pgmagick#22]
How can I use this python wrapper to compare two images using graphic magic ?

**Comment by hhatto** [comment]
```python
from pgmagick import Image
from pgmagick import CompositeOperator as co

img_a = Image('a.jpg')
img_b = Image('b.jpg')

print(img_a.compare(img_b))     # False
print(img_a.compare(img_a))     # True

img_a.composite(img_b, 0, 0, co.DifferenceCompositeOp)
img_a.write('diff.jpg')
```

How about is this?

**Comment by rohitsinha54** [comment]
@hhatto Thanks for the reply. 
I tried doing your suggestion but my execution fails with: 

```
ImportError: dlopen(/Users/rsinha/work/suit/venv/lib/python3.6/site-packages/pgmagick/_pgmagick.cpython-36m-darwin.so, 2): Symbol not found: _PyClass_Type
  Referenced from: /usr/local/opt/boost-python/lib/libboost_python-mt.dylib
  Expected in: flat namespace
 in /usr/local/opt/boost-python/lib/libboost_python-mt.dylib
```

My project is in Python 3. Any idea what might be the issue ?

**Comment by hhatto** [comment]
`boost-python` install with homebrew, add `--with-python3` option 
```
$ brew reinstall boost-python --with-python3
$ pip install pgmagick
```

**Comment by rohitsinha54** [comment]
Thanks for the prompt reply. I will try this tonight.

**Comment by rohitsinha54** [comment]
After doing this I see the following error:

```
ImportError: dlopen(/Users/rsinha/work/suit/venv/lib/python3.6/site-packages/pgmagick/_pgmagick.cpython-36m-darwin.so, 2): Symbol not found: __ZN6Magick22DrawableCompositeImage6magickESs
  Referenced from: /Users/rsinha/work/suit/venv/lib/python3.6/site-packages/pgmagick/_pgmagick.cpython-36m-darwin.so
  Expected in: flat namespace
 in /Users/rsinha/work/suit/venv/lib/python3.6/site-packages/pgmagick/_pgmagick.cpython-36m-darwin.so
```
Any idea ?

**Comment by hhatto** [comment]
Did you install `pgmagick` with `--upgrade` option?
```
$ pip install --upgrade pgmagick
```

**Comment by rohitsinha54** [comment]
Yes I did. 
I did pip3 uninstall pgmagick and then pip install --upgrade pgmagick. I still see the same error

```
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/helpers/pycharm/utrunner.py", line 161, in <module>
    module = loadSource(a[0])
  File "/Applications/PyCharm.app/Contents/helpers/pycharm/utrunner.py", line 65, in loadSource
    module = imp.load_source(moduleName, fileName)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 675, in _load
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/Users/rsinha/work/suit/RandomTest.py", line 2, in <module>
    from pgmagick import Image
  File "/Users/rsinha/work/suit/venv/lib/python3.6/site-packages/pgmagick/__init__.py", line 1, in <module>
    from pgmagick import _pgmagick
ImportError: dlopen(/Users/rsinha/work/suit/venv/lib/python3.6/site-packages/pgmagick/_pgmagick.cpython-36m-darwin.so, 2): Symbol not found: __ZN6Magick22DrawableCompositeImage6magickESs
  Referenced from: /Users/rsinha/work/suit/venv/lib/python3.6/site-packages/pgmagick/_pgmagick.cpython-36m-darwin.so
  Expected in: flat namespace
 in /Users/rsinha/work/suit/venv/lib/python3.6/site-packages/pgmagick/_pgmagick.cpython-36m-darwin.so
```
