### ISSUE TITLE
Unable to read font

### ISSUE THREAD

**Issue by deepbodra96** [hhatto/pgmagick#48]
I am getting this error
**RuntimeError: Magick: Unable to read font (n019003l.pfb) reported by ..\..\magick\annotate.c:1202 (RenderFreetype)**
at line 'img.draw(text)'
I have ghostscript installed
> 
from pgmagick import Image, DrawableCircle,DrawableText
img = Image('./images/1.jpg')
circle = DrawableCircle(100, 100, 20, 20)
img.draw(circle)
img.fontPointsize(160)
text = DrawableText(30, 250, "Hello pgmagick")
img.draw(text)
img.write('./images/draw_over_image_1.png')

Help would be appreciated!

**Comment by hhatto** [comment]
The following is What likely to be helpful to you?
https://www.hexacosa.net/blog/detail/185/

**Comment by deepbodra96** [comment]
Thank you very much for hearing me out.
I apologize for not mentioning my OS in the issue. I have winOS

I ran this command
>system_profiler -xml SPFontsDataType > fontset.xml

error:system_profiler is not recognized as an internal or external command.

executing mgkgen.py gives this error

**Traceback (most recent call last):
  File "mgkgen.py", line 144, in <module>
    main()
  File "mgkgen.py", line 81, in main
    with Popen(["system_profiler", "-xml", "SPFontsDataType"], stdout=PIPE) as proc:
  File "D:\Installs\IT\Python\Python35\lib\subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "D:\Installs\IT\Python\Python35\lib\subprocess.py", line 957, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified**
