### ISSUE TITLE
ImportError undefined symbol

### ISSUE THREAD

**Issue by lanery** [hhatto/pgmagick#53]
Running `CentOS Linux release 7.5.1804` and python 3.6

Followed
```
$ yum install GraphicsMagick-c++-devel
$ yum install boost-devel
$ pip install pgmagick
```
Tried importing
```
>>> from pgmagick import _pgmagick
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/catmaid/miniconda/envs/catmaid/lib/python3.6/site-packages/pgmagick/__init__.py", line 1, in <module>
    from pgmagick import _pgmagick
ImportError: /home/catmaid/miniconda/envs/catmaid/lib/python3.6/site-packages/pgmagick/_pgmagick.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN5boost6python6detail11init_moduleER11PyModuleDefPFvvE
```

`ldd` results
```
$ ldd _pgmagick.cpython-36m-x86_64-linux-gnu.so
        linux-vdso.so.1 =>  (0x00007ffcca1c8000)
        libboost_python-mt.so.1.53.0 => /lib64/libboost_python-mt.so.1.53.0 (0x00007f5e5e370000)
        libGraphicsMagick++-Q16.so.12 => /lib64/libGraphicsMagick++-Q16.so.12 (0x00007f5e5e100000)
        libstdc++.so.6 => /home/catmaid/miniconda/envs/catmaid/lib/libstdc++.so.6 (0x00007f5e5ddc6000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f5e5dac4000)
        libgcc_s.so.1 => /home/catmaid/miniconda/envs/catmaid/lib/libgcc_s.so.1 (0x00007f5e5d8b2000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f5e5d696000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f5e5d2c9000)
        libutil.so.1 => /lib64/libutil.so.1 (0x00007f5e5d0c6000)
        libpython2.7.so.1.0 => /lib64/libpython2.7.so.1.0 (0x00007f5e5ccfa000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f5e5caf6000)
        librt.so.1 => /lib64/librt.so.1 (0x00007f5e5c8ee000)
        libGraphicsMagick-Q16.so.3 => /lib64/libGraphicsMagick-Q16.so.3 (0x00007f5e5c518000)
        liblcms2.so.2 => /lib64/liblcms2.so.2 (0x00007f5e5c2be000)
        libfreetype.so.6 => /home/catmaid/miniconda/envs/catmaid/lib/libfreetype.so.6 (0x00007f5e5c017000)
        libXext.so.6 => /lib64/libXext.so.6 (0x00007f5e5be05000)
        libSM.so.6 => /lib64/libSM.so.6 (0x00007f5e5bbfd000)
        libICE.so.6 => /lib64/libICE.so.6 (0x00007f5e5b9e1000)
        libX11.so.6 => /lib64/libX11.so.6 (0x00007f5e5b6a3000)
        liblzma.so.5 => /home/catmaid/miniconda/envs/catmaid/lib/liblzma.so.5 (0x00007f5e5b47d000)
        libbz2.so.1 => /lib64/libbz2.so.1 (0x00007f5e5b26d000)
        libz.so.1 => /home/catmaid/miniconda/envs/catmaid/lib/libz.so.1 (0x00007f5e5b056000)
        libltdl.so.7 => /lib64/libltdl.so.7 (0x00007f5e5ae4c000)
        libgomp.so.1 => /home/catmaid/miniconda/envs/catmaid/lib/libgomp.so.1 (0x00007f5e5ac29000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f5e5eaf3000)
        libpng16.so.16 => /home/catmaid/miniconda/envs/catmaid/lib/./libpng16.so.16 (0x00007f5e5a9f2000)
        libuuid.so.1 => /lib64/libuuid.so.1 (0x00007f5e5a7ed000)
        libxcb.so.1 => /home/catmaid/miniconda/envs/catmaid/lib/libxcb.so.1 (0x00007f5e5a5c4000)
        libXau.so.6 => /lib64/libXau.so.6 (0x00007f5e5a3c0000)
```

**Comment by lanery** [comment]
I think maybe it's related to this? 
https://github.com/hhatto/pgmagick/issues/45#issuecomment-401325179

If so, how do I install `libboost-python3`?

**Comment by lanery** [comment]
Including the install log

[pgmagick_install.log](https://github.com/hhatto/pgmagick/files/2773657/pgmagick_install.log)

**Comment by hhatto** [comment]
@lanery 

Did you install Python 3.6 from the source code?
If so, boost-python must also be installed from the source code and linked with that boost-python.

**Comment by lanery** [comment]
No I believe python 3.6 was installed miniconda. Should I try reinstalling boost-python?

**Comment by hhatto** [comment]
> Should I try reinstalling boost-python?

yes.

Time has passed, so close it once. Please reopen if necessary.
