### ISSUE TITLE
ImportError: cannot import name _pgmagick

### ISSUE THREAD

**Issue by fraxinas** [hhatto/pgmagick#7]
After successful build (from source) and installation, i can't import pgmagick.
Python 2.7.11 (default, Mar 31 2016, 06:18:34) 
[GCC 5.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pgmagick
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pgmagick/__init__.py", line 1, in <module>
    from pgmagick import _pgmagick
ImportError: cannot import name _pgmagick

relevant versions:
pgmagick-0.6.1
extra/boost 1.60.0-4 [installed]
$ GraphicsMagick-config --version
1.3.23
GraphicsMagick++-config --version
1.3.23
$ uname -a
Linux fox 4.4.5-1-ARCH #1 SMP PREEMPT Thu Mar 10 07:38:19 CET 2016 x86_64 GNU/Linux

**Comment by hhatto** [comment]
Hi

I'm trying to install, use Arch Linux. ( [with vagrant](https://github.com/terrywang/vagrantboxes/blob/master/archlinux-x86_64.md) )
Either the installation of python2 and python3 was successful.

```
(py2pgmagick) [vagrant@archlinux ~]$ uname -a
Linux archlinux.vagrant.vm 4.5.0-1-ARCH #1 SMP PREEMPT Tue Mar 15 09:41:03 CET 2016 x86_64 GNU/Linux
(py2pgmagick) [vagrant@archlinux ~]$ python
Python 2.7.11 (default, Mar 31 2016, 06:18:34)
[GCC 5.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pgmagick
>>>
(py2pgmagick) [vagrant@archlinux ~]$ workon py3pgmagick
(py3pgmagick) [vagrant@archlinux ~]$ python
Python 3.5.1 (default, Mar  3 2016, 09:29:07)
[GCC 5.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pgmagick
>>>
```

Could you tell me the installation path of the `_pgmagick.so` file path?
In my environment, the results are as follows:
```
$ sudo updatedb && locate _pgmagick
/home/vagrant/.virtualenvs/py2pgmagick/lib/python2.7/site-packages/pgmagick/_pgmagick.so
/home/vagrant/.virtualenvs/py3pgmagick/lib/python3.5/site-packages/pgmagick/_pgmagick.cpython-35m-x86_64-linux-gnu.so
```

**Comment by fraxinas** [comment]
こんにちは、はっとさん、わかりました　：）
but I'm afraid there isn't any shared object file at all. there's only 
/usr/lib/python2.7/site-packages/pgmagick-0.6.1-py2.7-linux-x86_64.egg
i did indeed intend to install it for python2, not python3. so in python3 there it expectedly says:
`No module named 'pgmagick'.`

My installation procedure was as follows:
`yaourt graphicsmagick`
`tar -xvf pgmagick-0.6.1.tar.gz`
`cd pgmagick-0.6.1`
`more README.rst`
`./configure --enable-shared=yes`
which didn't work because there is no configure.ac, the README is wrong
`cd pgmagick`
`make`
the compilation stopped with an error similar to [https://github.com/hhatto/pgmagick/issues/3], so instead i used the build script
`cd ..`
`sudo python ./setup.py build`
`sudo python ./setup.py install --verbose`
`python`
after there was still the import problem, i tried manually re-installing the egg
`sudo easy_install-2.7 --verbose ./dist/pgmagick-0.6.1-py2.7-linux-x86_64.egg`
still no success

**Comment by hhatto** [comment]
How to install from the source need only `python setup.py install` or `pip install .`
```
$ cd pgmagick
$ sudo pip install .
      or
$ sudo python setup.py install
```

Could you attach a `python setup.py install` 's complete log or URL?
For example : https://gist.github.com/hhatto/b765a6d2b1be1ec82de405e0891f0ad7

**Comment by fraxinas** [comment]
i don't have pip so I used the setup.py script to install
here's the install log:
http://pastie.org/10807961

**Comment by hhatto** [comment]
Current working directory is not pgmagick directory?

```
$ cd pgmagick
$ ls
CHANGELOG          Makefile           build/             example/           pip.log            src/
LICENSE            README.rst         dist/              pgmagick/          script/            test/
MANIFEST.in        benchmark/         docs/              pgmagick.egg-info/ setup.py
$ python
Python 2.7.11 (default, Dec  5 2015, 14:44:47)
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.1.76)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pgmagick
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pgmagick/__init__.py", line 1, in <module>
    from pgmagick import _pgmagick
ImportError: cannot import name _pgmagick
```

**Comment by fraxinas** [comment]
```
[fraxinas@fox /net/dream/microcontroller/photobooth/pgmagick-0.6.1]$ ls
LICENSE  MANIFEST.in  Makefile  PKG-INFO  README.rst  build  dist  pgmagick  pgmagick.egg-info  setup.cfg  setup.py  src  test
[fraxinas@fox /net/dream/microcontroller/photobooth/pgmagick-0.6.1]$ python
Python 2.7.11 (default, Mar 31 2016, 06:18:34) 
[GCC 5.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pgmagick
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pgmagick/__init__.py", line 1, in <module>
    from pgmagick import _pgmagick
ImportError: cannot import name _pgmagick
[fraxinas@fox /net/dream/microcontroller/photobooth/pgmagick-0.6.1]$ cd pgmagick
[fraxinas@fox /net/dream/microcontroller/photobooth/pgmagick-0.6.1/pgmagick]$ ls
__init__.py  __init__.pyc  _version.py  api.py
[fraxinas@fox /net/dream/microcontroller/photobooth/pgmagick-0.6.1/pgmagick]$ python
Python 2.7.11 (default, Mar 31 2016, 06:18:34) 
[GCC 5.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pgmagick
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/pgmagick/__init__.py", line 1, in <module>
    from pgmagick import _pgmagick
  File "build/bdist.linux-x86_64/egg/pgmagick/_pgmagick.py", line 7, in <module>
  File "build/bdist.linux-x86_64/egg/pgmagick/_pgmagick.py", line 3, in __bootstrap__
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2900, in <module>
    @_call_aside
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2886, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2913, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 626, in _build_master
    ws = cls()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 619, in __init__
    self.add_entry(entry)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 675, in add_entry
    for dist in find_distributions(entry, True):
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1955, in find_on_path
    path_item, entry, metadata, precedence=DEVELOP_DIST
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2343, in from_location
    py_version=py_version, platform=platform, **kw
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2660, in _reload_version
    md_version = _version_from_file(self._get_metadata(self.PKG_INFO))
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2308, in _version_from_file
    line = next(iter(version_lines), '')
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2476, in _get_metadata
    for line in self.get_metadata_lines(name):
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1456, in get_metadata_lines
    return yield_lines(self.get_metadata(name))
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1448, in get_metadata
    return self._get(self._fn(self.egg_info, name))
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1559, in _get
    with open(path, 'rb') as stream:
IOError: [Errno 13] Permission denied: '/usr/lib/python2.7/site-packages/protobuf-3.0.0a1-py2.7.egg-info/PKG-INFO'

```

**Comment by hhatto** [comment]
Is the behavior of the as expected:
```
[fraxinas@fox /net/dream/microcontroller/photobooth/pgmagick-0.6.1]$ ls
LICENSE  MANIFEST.in  Makefile  PKG-INFO  README.rst  build  dist  pgmagick  pgmagick.egg-info  setup.cfg  setup.py  src  test
[fraxinas@fox /net/dream/microcontroller/photobooth/pgmagick-0.6.1]$ python
Python 2.7.11 (default, Mar 31 2016, 06:18:34) 
[GCC 5.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pgmagick
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pgmagick/__init__.py", line 1, in <module>
    from pgmagick import _pgmagick
ImportError: cannot import name _pgmagick
```

following result is the other problem. 
Please check the permissions of `/usr/lib/python2.7/site-packages/protobuf-3.0.0a1-py2.7.egg-info/PKG-INFO` file.
```
[fraxinas@fox /net/dream/microcontroller/photobooth/pgmagick-0.6.1]$ cd pgmagick
[fraxinas@fox /net/dream/microcontroller/photobooth/pgmagick-0.6.1/pgmagick]$ ls
__init__.py  __init__.pyc  _version.py  api.py
[fraxinas@fox /net/dream/microcontroller/photobooth/pgmagick-0.6.1/pgmagick]$ python
Python 2.7.11 (default, Mar 31 2016, 06:18:34) 
[GCC 5.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pgmagick
   :
   :
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1456, in get_metadata_lines
    return yield_lines(self.get_metadata(name))
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1448, in get_metadata
    return self._get(self._fn(self.egg_info, name))
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1559, in _get
    with open(path, 'rb') as stream:
IOError: [Errno 13] Permission denied: '/usr/lib/python2.7/site-packages/protobuf-3.0.0a1-py2.7.egg-info/PKG-INFO'
```

**Comment by fraxinas** [comment]
ありがとうございます。
`sudo chmod a+r /usr/lib/python2.7/site-packages/protobuf-3.0.0a1-py2.7.egg-info/ -R`
made it work.
it seems, the installer set the wrong permissions

**Comment by hhatto** [comment]
good luck 😄
