### ISSUE TITLE
pgmagick/_pgmagick.cpython-36m-x86_64-linux-gnu.so: undefined symbol

### ISSUE THREAD

**Issue by snakecy** [hhatto/pgmagick#71]

**Comment by hhatto** [comment]
@snakecy 
Thanks for reporting.
Can you tell me about your environment?

## Your Environment
* Python version:
* pgmagick version:
* Platform: windows, linux, macOSX, and other OS...

**Comment by snakecy** [comment]
> @snakecy
> Thanks for reporting.
> Can you tell me about your environment?
> 
> ## Your Environment
> * Python version:
> * pgmagick version:
> * Platform: windows, linux, macOSX, and other OS...

python  version: 3.6.10
pgmagick version: 0.7.6
Platform: CentOS 7.6


error:
python demo.py
```
Traceback (most recent call last):
  File "demo.py", line 112, in <module>
    get_magick()
  File "demo.py", line 99, in get_magick
    from pgmagick import Image
  File "/home/xx/anaconda3/envs/py36/lib/python3.6/site-packages/pgmagick/__init__.py", line 1, in <module>
    from pgmagick import _pgmagick
ImportError: /home/xx/anaconda3/envs/py36/lib/python3.6/site-packages/pgmagick/_pgmagick.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN5boost6python6detail11init_moduleER11PyModuleDefPFvvE
```

**Comment by yanchunhuo** [comment]
the same  error：
python version: 3.6.8
pgmagick version: 0.7.6
Platform: CentOS 7.6

======================
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/admin/AutomationTestEnv/lib64/python3.6/site-packages/pgmagick/__init__.py", line 1, in <module>
    from pgmagick import _pgmagick
ImportError: /home/admin/AutomationTestEnv/lib64/python3.6/site-packages/pgmagick/_pgmagick.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN6Magick5ColorC1Ehhhh
